import React, {useContext, useEffect} from 'react'
import Head from 'next/head'
import { FirebaseContext } from '../store/firebase-context'
import Router from 'next/router'
import '../styles/content.css'

export default function Home() {
  const FirebaseCtx = useContext(FirebaseContext)
  const { currentUser } = FirebaseCtx
  useEffect(() => {
    if(FirebaseCtx.canLogged) {
      if(currentUser) {
        Router.push('/home')
    } else {
        Router.push('/welcome')
    }
    }
  },[FirebaseCtx.canLogged])
  return (
    <div>
      <Head>
        <title>Katoweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}